---
- name: Proof include depending on environment 
  hosts: "{{ hosts }}"
  remote_user: thefoo 
  vars:
      master: false
      develop: false
  tasks:
    - name: Include tasks if env is develop
      include: envs/develop.yaml
      when: develop
    - name: Include tasks if env is master
      include: envs/master.yaml
      when: master
...
